class_name GameAudio
extends Node

# App-wide sound. Music loops (lobby, battle, instance) crossfade on the "Music" bus;
# effects are one-shots from assets/audio/sfx/<name>.ogg on the "SFX" bus. All of it
# is generated by tools/make_sfx.py and tools/make_music.py. The on/off switches for
# music and effects persist in user://audio.cfg.

const SFX_DIR: String = "res://assets/audio/sfx/"
const MUSIC_DIR: String = "res://assets/audio/music/"
const SETTINGS_PATH: String = "user://audio.cfg"
const VOICES: int = 24
const MUSIC_DB: float = -8.0
const SFX_DB: float = -1.0
const SILENT_DB: float = -60.0

var enabled: bool = true
var music_on: bool = true
var music_track: String = ""
var streams: Dictionary = {}
var voices: Array[AudioStreamPlayer] = []
var next_voice: int = 0
var decks: Array[AudioStreamPlayer] = []
var deck: int = 0
var fades: Array = [null, null]
var hum: AudioStreamPlayer
var last_played: Dictionary = {}

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	ensure_bus("Music", MUSIC_DB)
	ensure_bus("SFX", SFX_DB)
	load_settings()
	for i in range(VOICES):
		voices.append(make_player("SFX"))
	for i in range(2):
		decks.append(make_player("Music"))
	hum = make_player("SFX")
	apply_settings()

func _exit_tree() -> void:
	stop_all()

func stop_all() -> void:
	# Leaves no playback running (quitting mid-sound would leak the Ogg playbacks).
	for player in voices + decks + [hum]:
		if is_instance_valid(player):
			player.stop()
			player.stream = null
	streams.clear()

func make_player(bus: String) -> AudioStreamPlayer:
	var player: AudioStreamPlayer = AudioStreamPlayer.new()
	player.bus = bus
	add_child(player)
	return player

static func ensure_bus(bus: String, volume: float) -> void:
	if AudioServer.get_bus_index(bus) != -1:
		return
	AudioServer.add_bus()
	var index: int = AudioServer.bus_count - 1
	AudioServer.set_bus_name(index, bus)
	AudioServer.set_bus_send(index, "Master")
	AudioServer.set_bus_volume_db(index, volume)

func stream(path: String) -> AudioStream:
	if streams.has(path):
		return streams[path]
	var result: AudioStream = null
	if ResourceLoader.exists(path):
		result = load(path)
	elif FileAccess.file_exists(path):
		# Not imported yet (game launched without the editor): decode the file directly.
		result = AudioStreamOggVorbis.load_from_file(path)
	streams[path] = result
	return result

func has_sound(sound: String) -> bool:
	return stream(SFX_DIR + sound + ".ogg") != null

func play(sound: String, volume_db: float = 0.0, pitch: float = 1.0, throttle_ms: int = 45) -> void:
	# The same effect fired many times at once (three balls, fruit rain) plays once.
	if not enabled or sound == "":
		return
	var now: int = Time.get_ticks_msec()
	if now - int(last_played.get(sound, -100000)) < throttle_ms:
		return
	var clip: AudioStream = stream(SFX_DIR + sound + ".ogg")
	if clip == null:
		return
	last_played[sound] = now
	var player: AudioStreamPlayer = null
	for i in range(VOICES):
		var candidate: AudioStreamPlayer = voices[(next_voice + i) % VOICES]
		if not candidate.playing:
			player = candidate
			break
	if player == null:
		player = voices[next_voice]
	next_voice = (voices.find(player) + 1) % VOICES
	player.stream = clip
	player.volume_db = volume_db
	player.pitch_scale = pitch
	player.play()

func play_music(track: String, fade: float = 1.4) -> void:
	# "" fades the music out. The same track keeps playing without a restart.
	if track == music_track:
		return
	music_track = track
	fade_deck(deck, SILENT_DB, fade, true)
	deck = 1 - deck
	if track == "" or not music_on:
		return
	var song: AudioStream = stream(MUSIC_DIR + track + ".ogg")
	if song == null:
		return
	if song is AudioStreamOggVorbis:
		song.loop = true
	var fresh: AudioStreamPlayer = decks[deck]
	fresh.stream = song
	fresh.volume_db = SILENT_DB
	fresh.play()
	fade_deck(deck, 0.0, fade * 0.8, false)

func fade_deck(index: int, target: float, seconds: float, stop_after: bool) -> void:
	var player: AudioStreamPlayer = decks[index]
	if fades[index] is Tween and fades[index].is_valid():
		fades[index].kill()
	if not player.playing:
		return
	var tween: Tween = create_tween()
	tween.tween_property(player, "volume_db", target, maxf(0.05, seconds)).set_trans(Tween.TRANS_SINE)
	if stop_after:
		tween.tween_callback(player.stop)
	fades[index] = tween

func set_charge(active: bool, power: float, volume_db: float = -4.0) -> void:
	# Hum that rises with the force bar while SPACE is held.
	if not enabled or not active:
		if hum.playing:
			hum.stop()
		return
	if not hum.playing:
		var clip: AudioStream = stream(SFX_DIR + "charge_loop.ogg")
		if clip == null:
			return
		if clip is AudioStreamOggVorbis:
			clip.loop = true
		hum.stream = clip
		hum.play()
	hum.volume_db = volume_db
	hum.pitch_scale = 0.75 + clampf(power, 0.0, 100.0) / 100.0 * 0.9

func set_music_on(value: bool) -> void:
	music_on = value
	apply_settings()
	save_settings()
	if value and music_track != "" and not decks[deck].playing:
		var track: String = music_track
		music_track = ""
		play_music(track, 0.6)

func set_sfx_on(value: bool) -> void:
	enabled = value
	apply_settings()
	save_settings()

func apply_settings() -> void:
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Music"), not music_on)
	AudioServer.set_bus_mute(AudioServer.get_bus_index("SFX"), not enabled)
	if not enabled and is_instance_valid(hum):
		hum.stop()

func load_settings() -> void:
	var config: ConfigFile = ConfigFile.new()
	if config.load(SETTINGS_PATH) == OK:
		music_on = bool(config.get_value("audio", "music", true))
		enabled = bool(config.get_value("audio", "sfx", true))

func save_settings() -> void:
	var config: ConfigFile = ConfigFile.new()
	config.set_value("audio", "music", music_on)
	config.set_value("audio", "sfx", enabled)
	config.save(SETTINGS_PATH)
